'use strict';
(function (api) {
	class Volcano extends api._ProceduralScene {
		constructor(w, h, cfg, seed) {
			super('volcano', w, h, cfg, seed);
		}
	}

	api.presets['volcano'] = [
		{
			key: 'sleeping-cone',
			label: 'sleeping cone',
			config: {
				intro_glow: 0.1,
				ending_glow: 0.06,
				horizon: 0.86,
				cone_height: 26,
				cone_width: 48,
				crater_width: 7,
				slope_jitter: 1.4,
				glow: 0.3,
				smoke: 0.16,
				smoke_height: 14,
				hue: 16,
				hue_sp: 12,
				sat: 0.6,
				lmin: 0.16,
				lmax: 0.76,
				eruption_p: 0.0001,
				smolder_p: 0.0008,
				flare_p: 0.0006,
			},
		},
		{
			key: 'smoldering-crater',
			label: 'smoldering crater',
			config: {
				horizon: 0.86,
				cone_height: 28,
				cone_width: 46,
				crater_width: 9,
				slope_jitter: 1.6,
				glow: 0.55,
				smoke: 0.42,
				smoke_height: 22,
				hue: 18,
				hue_sp: 18,
				sat: 0.78,
				lmin: 0.18,
				lmax: 0.9,
				eruption_p: 0.0004,
				flare_p: 0.0014,
				smolder_p: 0.0006,
				eruption_height: 22,
				eruption_mult: 2.1,
			},
		},
		{
			key: 'active-vent',
			label: 'active vent',
			config: {
				intro_glow: 0.22,
				horizon: 0.84,
				cone_height: 30,
				cone_width: 48,
				crater_width: 10,
				slope_jitter: 1.8,
				glow: 0.78,
				smoke: 0.48,
				smoke_height: 28,
				hue: 14,
				hue_sp: 22,
				sat: 0.88,
				lmin: 0.22,
				lmax: 0.96,
				eruption_p: 0.0014,
				eruption_dur: 96,
				eruption_height: 32,
				eruption_mult: 2.7,
				flare_p: 0.0018,
				flare_mult: 2.0,
			},
		},
		{
			key: 'ember-burst',
			label: 'ember burst',
			config: {
				intro_glow: 0.18,
				ending_glow: 0.16,
				horizon: 0.88,
				cone_height: 24,
				cone_width: 42,
				crater_width: 12,
				slope_jitter: 1.2,
				glow: 0.7,
				smoke: 0.22,
				smoke_height: 16,
				hue: 22,
				hue_sp: 26,
				sat: 0.9,
				lmin: 0.2,
				lmax: 0.98,
				eruption_p: 0.0022,
				eruption_dur: 60,
				eruption_height: 36,
				eruption_mult: 3.0,
				flare_p: 0.0024,
				flare_mult: 2.2,
				smolder_p: 0.0004,
			},
		},
	];
	api.effects['volcano'] = Volcano;
})(window.AmbienceSim);
