apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambience-edge
  namespace: ambience
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ambience
      component: edge
  template:
    metadata:
      labels:
        app: ambience
        component: edge
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: ambience
          image: romainecr.azurecr.io/ambience:latest
          imagePullPolicy: Always
          env:
            - name: AMBIENCE_ROLE
              value: edge
            - name: AMBIENCE_AUTHORITY_URL
              value: http://ambience-authority:8080
            - name: AMBIENCE_SHUTDOWN_DRAIN
              value: 12s
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
