domain:
  host: ambience.dev.romaine.life
  tlsSecretName: ambience-dev-tls

image:
  tag: 38391ed

edge:
  replicas: 1
  terminationGracePeriodSeconds: 3
  shutdownDrain: 1s
  webOverride:
    enabled: true

pdb:
  enabled: false
