{{- if eq (include "ambience.renderHot" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ambience.name" . }}-authority
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ambience.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "ambience.authoritySelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ambience.name" . }}-authority-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ambience.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ambience.authoritySelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
