{{- if and .Values.route.enabled (eq (include "ambience.renderWarm" .) "true") }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ambience.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- if not .Values.route.externalDns.enabled }}
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
  {{- end }}
  labels:
    {{- include "ambience.labels" . | nindent 4 }}
spec:
  hostnames:
    - {{ include "ambience.domainHost" . }}
  parentRefs:
    - group: {{ .Values.gateway.parentGateway.group }}
      kind: {{ .Values.gateway.parentGateway.kind }}
      name: {{ .Values.gateway.parentGateway.name }}
      namespace: {{ .Values.gateway.parentGateway.namespace }}
    - group: gateway.networking.x-k8s.io
      kind: XListenerSet
      name: {{ include "ambience.routeListenerSetName" . }}
      namespace: {{ include "ambience.routeListenerSetNamespace" . }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: {{ .Values.route.requestTimeout }}
        backendRequest: {{ .Values.route.backendRequestTimeout }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "ambience.name" . }}
          port: {{ .Values.service.port }}
          weight: 1
{{- end }}
