{{- if and .Values.oauth.externalSecret.enabled .Values.oauth.externalSecret.createStore (not (eq (include "ambience.isTestEnv" .) "true")) }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.oauth.externalSecret.storeName | quote }}
  labels:
    {{- include "ambience.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.oauth.externalSecret.vaultUrl | quote }}
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
{{- end }}
