apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.authority.storage.existingClaim }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ambience.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.authority.storage.size }}
